# Generated by Django 4.2 on 2023-04-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_educationmodule_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodule',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
